# Generated by Django 5.2.3 on 2025-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
